#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Derive the GitHub owner/repo from the git remote, for building direct links
# later (secrets page, Actions tab). Falls back to a placeholder if unknown.
GITHUB_SLUG=""
if REMOTE_URL=$(git remote get-url origin 2>/dev/null); then
  GITHUB_SLUG=$(printf '%s' "$REMOTE_URL" \
    | sed -E 's#^git@github\.com:##; s#^https://github\.com/##; s#\.git$##')
fi
[[ -z "$GITHUB_SLUG" ]] && GITHUB_SLUG="<your-github-owner>/<your-repo>"

banner "Deploy baseApp to a free-tier AWS EC2 instance"

# ── Stage 1: AWS account + region ──────────────────────────────────────────
stage "AWS account & region"
say "Free tier gives you 750 hrs/month of a t2.micro or t3.micro instance for"
say "12 months from account creation — enough to run this app continuously."
if confirm "Do you already have an AWS account?"; then
  open_url "https://console.aws.amazon.com/"
  step "Sign in."
else
  open_url "https://portal.aws.amazon.com/billing/signup"
  step "Create an account (needs a card on file, but free-tier usage is \$0)."
  pause "Come back here once you're signed in to the console."
fi
say "Pick the AWS region you want to deploy into (top-right region switcher)."
say "Closer to you/your users = lower latency. e.g. us-east-1, eu-west-1, ap-south-1."
ask REGION "Which region code will you use?"
write_env AWS_REGION "$REGION"

# ── Stage 2: your public IP (to lock down SSH) ─────────────────────────────
stage "Your public IP (for locking down SSH)"
say "We'll restrict SSH access to just your current IP instead of the whole internet."
DETECTED_IP=$(curl -fsS --max-time 5 https://checkip.amazonaws.com 2>/dev/null | tr -d '[:space:]' || true)
if [[ -n "$DETECTED_IP" ]]; then
  say "Detected your public IP as: $DETECTED_IP"
else
  warn "couldn't auto-detect your IP (offline or blocked)."
fi
ask MY_IP "Confirm/enter your public IP:${DETECTED_IP:+ (Enter to use the detected one)}"
[[ -z "$MY_IP" && -n "$DETECTED_IP" ]] && MY_IP="$DETECTED_IP"
say "You'll use $MY_IP/32 as the allowed source for SSH in the next stage."

# ── Stage 3: key pair ───────────────────────────────────────────────────────
stage "Create an SSH key pair"
open_url "https://${REGION}.console.aws.amazon.com/ec2/home?region=${REGION}#KeyPairs:"
step "Click 'Create key pair'."
step "Name it baseapp-key. Type: RSA. Format: .pem."
step "Click Create — it downloads baseapp-key.pem to your computer. Don't lose it,"
step "AWS won't let you download it again."
ask PEM_PATH "Full path to the downloaded .pem file:"
if [[ -f "$PEM_PATH" ]]; then
  chmod 400 "$PEM_PATH"
  say "Set permissions to 400 on $PEM_PATH (required for SSH)."
else
  warn "no file found at that path yet — fix the path before Stage 7 (SSH in)."
fi
write_env EC2_KEY_PAIR_NAME "baseapp-key"
write_env EC2_PEM_PATH "$PEM_PATH"

# ── Stage 4: security group ────────────────────────────────────────────────
stage "Create a security group (firewall rules)"
say "Rules: SSH (22) from only your IP, HTTP (80) from anywhere. Keep 4000 and"
say "5174 closed to the public internet — those stay internal to the instance."
open_url "https://${REGION}.console.aws.amazon.com/ec2/home?region=${REGION}#SecurityGroups:"
step "Click 'Create security group'. Name it baseapp-sg."
step "Inbound rules → Add rule: Type=SSH, Source=Custom, ${MY_IP}/32"
step "Add rule: Type=HTTP, Source=Anywhere (0.0.0.0/0)"
step "Leave outbound rules at their default (all traffic allowed)."
step "Click 'Create security group'."
confirm "Security group baseapp-sg created with those two inbound rules?"
write_env EC2_SECURITY_GROUP "baseapp-sg"

# ── Stage 5: launch the instance ───────────────────────────────────────────
stage "Launch the EC2 instance"
open_url "https://${REGION}.console.aws.amazon.com/ec2/home?region=${REGION}#LaunchInstances:"
step "Name: baseapp-server"
step "Application and OS Images: Ubuntu Server 24.04 LTS (should be Free tier eligible)"
step "Instance type: t2.micro or t3.micro — pick whichever is tagged 'Free tier eligible'"
step "Key pair: baseapp-key"
step "Network settings → Select existing security group → baseapp-sg"
step "Storage: leave the default (up to 30 GiB is within the free tier)"
step "Click 'Launch instance'"
pause "Wait until the instance state shows 'Running', then continue."
ask INSTANCE_PUBLIC_IP "Paste the instance's Public IPv4 address (shown on the instance details page):"

# ── Stage 6: Elastic IP ─────────────────────────────────────────────────────
stage "Attach a stable Elastic IP"
say "A plain public IP changes if the instance stops/restarts. An Elastic IP doesn't."
open_url "https://${REGION}.console.aws.amazon.com/ec2/home?region=${REGION}#Addresses:"
step "Click 'Allocate Elastic IP address' → Allocate."
step "Select the new address → Actions → 'Associate Elastic IP address'."
step "Instance: baseapp-server → Associate."
ask ELASTIC_IP "Paste the Elastic IP address:"
write_env EC2_HOST "$ELASTIC_IP"
say "This is the address GitHub Actions will SSH into for every deploy."

# ── Stage 7: install Docker + git on the instance ──────────────────────────
stage "Install Docker on the instance"
say "SSH in with the command below, then run the install commands on the instance."
say ""
say "  ssh -i \"$PEM_PATH\" ubuntu@$ELASTIC_IP"
say ""
step "Once connected, run:"
say "  curl -fsSL https://get.docker.com | sudo sh"
say "  sudo usermod -aG docker \$USER"
say "  sudo apt-get update -y && sudo apt-get install -y git"
step "Log out and back in (or run 'newgrp docker') so the docker group takes effect."
confirm "Docker and git installed on the instance?"

# ── Stage 8: clone the repo + first manual run ─────────────────────────────
stage "Clone the repo and do one manual test run"
ask REPO_URL "Your repo's clone URL (https://github.com/... or git@github.com:...):"
say "Back in your SSH session on the instance, run:"
say ""
say "  git clone $REPO_URL baseApp"
say "  cd baseApp"
say "  docker compose up -d --build"
say ""
step "Confirm both containers are serving traffic WITHOUT opening any new public"
step "ports — from the same SSH session run:"
say "  curl -I localhost:4000/api/message"
say "  curl -I localhost:5174"
say "Both should return HTTP 200."
note "(Optional: temporarily add an inbound rule for port 5174 in baseapp-sg if"
note "you want to open http://$ELASTIC_IP:5174 in your own browser right now —"
note "remove the rule again afterward. Not required for the automated deploy.)"
confirm "Both curl checks returned 200?"

# ── Stage 9: GitHub Actions secrets ────────────────────────────────────────
stage "Add GitHub secrets for CD"
say "The .github/workflows/cd.yml workflow reads three repo secrets to SSH in"
say "and redeploy: EC2_HOST, EC2_USER, EC2_SSH_KEY."
open_url "https://github.com/${GITHUB_SLUG}/settings/secrets/actions/new"
step "Name: EC2_HOST  →  Value: $ELASTIC_IP"
step "Save, then click 'New repository secret' again."
step "Name: EC2_USER  →  Value: ubuntu"
step "Save, then click 'New repository secret' again."
step "Name: EC2_SSH_KEY  →  Value: the FULL contents of $PEM_PATH (including the"
step "-----BEGIN/END----- lines), pasted as-is."
set_secret EC2_HOST "$ELASTIC_IP"
set_secret EC2_USER "ubuntu"
if [[ -f "$PEM_PATH" ]]; then
  EC2_SSH_KEY_VALUE=$(cat "$PEM_PATH")
  set_secret EC2_SSH_KEY "$EC2_SSH_KEY_VALUE"
else
  SKIPPED+=("GitHub secret EC2_SSH_KEY (couldn't read $PEM_PATH — set it manually)")
  warn "couldn't read the .pem file to auto-set EC2_SSH_KEY — use the web UI step above."
fi
note "The private key is intentionally NOT written to $ENV_FILE — only sent to"
note "the GitHub secret store."

# ── Stage 10: verify CI → CD end to end ────────────────────────────────────
stage "Verify the pipeline end to end"
say "Commit and push .github/workflows/ci.yml and cd.yml if you haven't already,"
say "then push any small change to main to trigger the pipeline."
open_url "https://github.com/${GITHUB_SLUG}/actions"
step "Watch the 'CI' run finish green."
step "Watch the 'CD' run start automatically right after and finish green."
step "Re-run the curl checks from Stage 8 on the instance to confirm the redeploy landed."
warn "Remember: server/index.js currently only allows localhost origins in CORS."
say "Update the origin list at the '// add production url' comment to include"
say "http://$ELASTIC_IP (or your real domain once you add one), then push again."
# ──────────────────────────────────────────────────────────────────────────

finish
